### ISSUE TITLE
disable sleep / lock while share/send is active

### ISSUE THREAD

**Issue by n8fr8** [tladesignz/AdParticipesCumCepis#1]
https://developer.apple.com/forums/thread/111810

UIApplication.shared.isIdleTimerDisabled = true

**Comment by n8fr8** [comment]
https://stackoverflow.com/questions/9412877/how-to-disable-iphone-ipad-auto-lock-while-app-is-in-foreground-mode

**Comment by tladesignz** [comment]
Yeah, thanks, forgot about this one. Will be interesting to see, if Apple allows us to make a nightlamp out of a mobile, just to keep the app running for serving websites.

It's an ugly hack for something which Apple is obviously not keen on happening. Otherwise, they would provide proper facilities for running web servers in the background.
